server:
  port: 8087
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  application:
    name: ai-service
  ai:
    openai:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus-2025-09-11
      embedding:
        options:
          model: text-embedding-v4
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        database-name: default
        collection-name: hmall_items
        embedding-dimension: 1536
        index-type: IVF_FLAT
        metric-type: COSINE
    chat:
      memory:
        type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root
      database: 0
  datasource:
    url: jdbc:mysql://192.168.88.131:3307/hm-reservation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.88.131:8848
      discovery:
        # namespace: hmall  <-- 暂时注释掉，确保和 item-service 在同一个 public 空间
        group: DEFAULT_GROUP
logging:
  level:
    com.alibaba.nacos.client.naming: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true